# 다중행 함수
SELECT SUM(SAL) FROM EMP;
SELECT ENAME, SAL FROM EMP;
SELECT ENAME, SUM(SAL) FROM EMP
GROUP BY ENAME;

#직원들의 전체 보너스 (COMM) 총합은?
SELECT SUM(COMM) FROM EMP;

#급여 합계
SELECT SUM(SAL),SUM(DISTINCT SAL), SUM(ALL SAL)
FROM EMP;

#총 직원의 수는?
SELECT COUNT(*) FROM EMP;

#30번 부서의 직원의 수는?
SELECT COUNT(*) FROM EMP
WHERE DEPTNO = 30;

#월급의 최솟값과 최댓값을 각각 구하기
SELECT DEPTNO, MAX(SAL),MIN(SAL)FROM EMP
GROUP BY DEPTNO ORDER BY MAX(SAL) DESC;
