# DEPT 테이블 복사 DEPT_TEMP
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;

#데이터 추가
#50번 부서 'DATABASE', 'SEOUL'
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (50, 'DATABASE', 'SEOUL');

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (60, 'NETWORK','BUSAN');

DESC DEPT_TEMP;

INSERT INTO DEPT_TEMP
VALUES (70, 'NETWORK2', 'ANDONG');

# NULL
INSERT INTO DEPT_TEMP (DEPTNO, LOC)
VALUES (90, 'INCHEON');

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (80, 'MOBILE', '');

SELECT * FROM DEPT_TEMP;

#날짜 데이터 입력
CREATE TABLE EMP_TEMP 
AS SELECT * FROM EMP WHERE 1<>1;

SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1111, '성춘향', 'PRESIDENT', NULL, '2001-01-01', 5000, 1000, 10);

INSERT INTO EMP_TEMP
VALUES (1111, '성춘향', 'PRESIDENT', NULL, TO_DATE('07/01/2001','DD/MM/YYYY'), 5000, 1000, 10);

INSERT INTO EMP_TEMP
VALUES (8888, '성춘향', 'PRESIDENT', NULL, SYSDATE, 5000, 1000, 10);

#UPDATE
CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT;

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL';

ROLLBACK;

DELETE FROM DEPT_TEMP2
WHERE DEPTNO = 40;

DELETE FROM DEPT_TEMP2
WHERE LOC = 'DALLAS';

SELECT * FROM DEPT_TEMP2;

COMMIT;

