#6-4 문자열 길이
SELECT ENAME, LENGTH (ENAME) FROM EMP;
#사원 이름의 길이가 5이상인 행 출력
SELECT ENAME, LENGTH (ENAME) FROM EMP
WHERE LENGTH (ENAME) >=6;
#한글 바이트 수
SELECT LENGTH ('한글'), LENGTHB ('한글') FROM DUAL;

#SUBSTR(,,) SUBSTR(,)
SELECT JOB,SUBSTR(JOB, 1, 2 ), SUBSTR(JOB, 3, 2) FROM EMP;

SELECT SUBSTR('900305',1,2),SUBSTR('900305',1,2) FROM DUAL;
# 주민번호 앞자리 뽑기
SELECT SUBSTR('990803-1111111', 1, 6 ) FROM DUAL;
SELECT SUBSTR('990803-1111111', 1, 2 ) FROM DUAL;
SELECT SUBSTR('990803-1111111', 8, 15 ) FROM DUAL;

#SUBSTR -1값
SELECT JOB, SUBSTR(JOB, -3) FROM EMP;
SELECT SUBSTR ('홍길동',-2) FROM DUAL;


#문자열에서 특정문자 위치를 찾는 INSTR 함수
SELECT INSTR ('안녕하세요','요')AS 위치 FROM DUAL;
# 검색 위치 변경
SELECT INSTR ('HELLO, ORACLE!','L'),
       INSTR ('HELLO, ORACLE!','L',5),
       INSTR ('HELLO, ORACLE!','L',2,2)
FROM DUAL;
