#P212 연습문제 1번
SELECT DEPTNO,TRUNC(AVG(SAL),0),MAX(SAL),MIN(SAL),COUNT(ENAME)AS CNT
FROM EMP
GROUP BY DEPTNO;

#P212 연습문제 2번
SELECT JOB,COUNT(*) FROM EMP
GROUP BY JOB
HAVING COUNT(*)>=3;

#P212 연습문제 3번
SELECT TO_CHAR(HIREDATE, 'YYYY')AS HIRE_YEAR ,DEPTNO,
COUNT(*) FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO
ORDER BY TO_CHAR(HIREDATE, 'YYYY');

#P212 연습문제 4번
SELECT NVL2(COMM,'O','X') AS EXIST_COMM, COUNT(*)AS CNT FROM EMP
GROUP BY NVL2(COMM,'O','X');
