#주민번호 앞자리
SELECT RPAD('971225-',14,'*')FROM DUAL;
#'HELLO' 소문자로 변경
SELECT LOWER('HELLO')FROM DUAL;
#'안녕' 문자열의 길이와 바이트 크기를 알려주세요.
SELECT LENGTH ('안녕'), LENGTHB ('안녕') FROM DUAL;

#P150 SQL 날짜함수들...
SELECT * FROM EMP;
SELECT ENAME HIREDATE FROM EMP;
DESC EMP;

SELECT SYSDATE AS NOW, 
  SYSDATE -1  AS 어제,
  SYSDATE +1  AS 내일
FROM DUAL;

#3개월 추의 날짜는?
SELECT SYSDATE, ADD_MONTHS(SYSDATE,3)FROM DUAL;
#입사 10주년이 되는 사원들의 데이터는?
SELECT EMPNO ,ENAME, HIREDATE,
       ADD_MONTHS (HIREDATE,120) AS WORK10YEAR
FROM EMP;
#입사 32년 미만인 사원 데이터 출력
SELECT EMPNO, ENAME, HIREDATE, SYSDATE FROM EMP
WHERE ADD_MONTHS(HIREDATE,500) > SYSDATE;

#SYSDATE ADD_MONTH 함수를 사용하여 현재 날짜와
#6개월 후 날짜가 출력되도록
SELECT SYSDATE, ADD_MONTHS(SYSDATE,6) FROM DUAL;

#두 날짜간의 개월수 차이를 구하는 함수(MONTHS_BETWEEN)
SELECT EMPNO, ENAME, HIREDATE,
        ROUND (MONTHS_BETWEEN(HIREDATE,SYSDATE),2)
        AS MONTH1,
        TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE),2)
        AS MONTH2
FROM EMP;
#달의 마지막 날짜 구하는 함수 NEXT_DAY, LAST_DAY
SELECT SYSDATE,
       NEXT_DAY(SYSDATE,'월요일'),
       LAST_DAY(SYSDATE),
       NEXT_DAY(NEXT_DAY(SYSDATE,'월요일'),'월요일')
FROM DUAL;

#6-29 ROUND함수 사용하여 날짜데이터 출력
SELECT SYSDATE,
       ROUND(SYSDATE,'CC') AS FORMAT_CC,
       ROUND(SYSDATE,'YYYY') AS FORMAT_YYYY,
       ROUND(SYSDATE,'Q') AS FORMAT_Q,
       ROUND(SYSDATE,'DDD') AS FORMAT_DDD,
       ROUND(SYSDATE,'HH') AS FORMAT_HH
FROM DUAL;

#프로그래밍과 직접 관련된 변환함수

#숫자와 문자열을 더하여 출력
SELECT EMPNO, ENAME, EMPNO+'500' FROM EMP
WHERE ENAME = 'KING';
DESC EMP;

#문자열과 숫자를 더하여 출력
SELECT EMPNO+'700', EMPNO, ENAME FROM EMP
WHERE ENAME = 'KING';

#형변환 함수
#TO_CHAR, TO_NUMBER, TO_DATE

#날짜 형식을 문자열로 출력하고 싶습니다.
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS 현재날짜시간
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY HH24:MI:SS') AS 현재날짜시간
FROM DUAL;

#월과 요일을 다양한 형식으로 출력하기
SELECT SYSDATE,
    TO_CHAR(SYSDATE,'MM'),
    TO_CHAR(SYSDATE,'MONTH'),
    TO_CHAR(SYSDATE,'DY'),
    TO_CHAR(SYSDATE,'DAY')
FROM DUAL;

#여러 언어로 날짜(월) 출력하기
SELECT SYSDATE,
    TO_CHAR(SYSDATE,'MON', 'NLS_DATE_LANGUAGE=JAPANESE')AS MON_JPN,
    TO_CHAR(SYSDATE,'MON', 'NLS_DATE_LANGUAGE=ENGLISH')AS MON_ENG,
    TO_CHAR(SYSDATE,'DAY', 'NLS_DATE_LANGUAGE=JAPANESE')AS DAY_JPN,
    TO_CHAR(SYSDATE,'DAY', 'NLS_DATE_LANGUAGE=ENGLISH')AS DAY_ENG
FROM DUAL;

#문자데이터를 날짜데이터로 변환하는 함수 TO_DATE
SELECT TO_DATE('2018-07-14','YYYY-MM-DD')AS DATE1
FROM DUAL;

#문자열의 숫자타입으로 변환하여면 TO_NUMVER
SELECT 1300-'1500','1300'+1500 FROM DUAL;
SELECT '1300' - '1500' FROM DUAL;
#에러
SELECT '1,300'-'1,500' FROM DUAL;

SELECT TO_NUMBER('1,300','999,999')
     -TO_NUMBER('1,500','999,999') AS RESULT
FROM DUAL;

#TO_CHAR, TO_NUMBER, TO_DATE 꼭기억!!!1

#TO_CHAR 급여출력
SELECT SAL, 
    TO_CHAR(SAL, '$999,999') AS 달러,
    TO_CHAR(SAL, 'L999,999') AS 원,
    TO_CHAR(SAL, '999,999.00') AS SAL1,
    TO_CHAR(SAL, '$000999999.99') AS SAL2,
    TO_CHAR(SAL, '$999,999.00') AS SAL1
FROM EMP;
