/* 컬럼 이름 생성 규칙
    1. 컬럼 이름은 문자로 시작해야 한다.
    2. 컬럼 이름은 30bytes 이하여야 한다.
    3. 한 테이블의 컬럼 이름은 중복될 수 없다.
    4. 컬럼 이름은 영문자(한글), 숫자(0-9), 특수문자 사용가능
    5. SQL 키워드는 컬럼 이름 등으로 사용할 수 없다.
*/

#테이블 만들기
CREATE TABLE EMP_DDL(
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    HIREDATE     DATE,
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2)
);

#테이블 구조 변경 ALTER
CREATE TABLE EMP_ALTER
AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

#컬럼 추가
ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

#TEL 컬럼 추가 VARCHAR2(20)
ALTER TABLE EMP_ALTER
ADD TEL VARCHAR2(20);

#TEL 컬럼 삭제
ALTER TABLE EMP_ALTER
 DROP COLUMN TEL;
 
COMMIT;

#TEL COLUMN 추가
ALTER TABLE EMP_ALTER
ADD TEL VARCHAR2(20);

ALTER TABLE EMP_ALTER
 DROP COLUMN TEL;
 
ALTER TABLE EMP_ALTER
 RENAME COLUMN HP TO TEL;

COMMIT;

#컬럼의 이름 변경하는게 아닌 타입을 바꾸고 싶을때
ALTER TABLE EMP_ALTER
 MODIFY EMPNO NUMBER(5);
 
DESC EMP_ALTER;

# ENAME : VARCHAR2(10) -> VARCHAR2(13)
ALTER TABLE EMP_ALTER
MODIFY ENAME VARCHAR2(13);

ALTER TABLE EMP_ALTER
RENAME COLUMN TEL TO PHONENUMBER;

#테이블의 이름을 변경해 보세요~~
RENAME EMP_ALTER TO EMP_RENAME;

SELECT * FROM EMP_RENAME;
COMMIT;

#테이블의 데이터를 강제로 삭제하는 명령어
TRUNCATE TABLE EMP_RENAME;
SLECT * FROM EMP_RENAME;
COMMIT;

DROP TABLE EMP_RENAME;

Q1
CREATE TABLE EMP_HW(
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    HIREDATE     DATE,
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2)
);

Q2
ALTER TABLE EMP_HW
 ADD BIGO VARCHAR2(20);
 
 DESC EMP_HW;
 
Q3
ALTER TABLE EMP_HW
 MODIFY BIGO VARCHAR2(30);

DESC EMP_HW;

Q4
ALTER TABLE EMP_HW
 RENAME COLUMN BIGO TO REMARK;
 
DESC EMP_HW;

Q5
DROP TABLE EMP_HW;

CREATE TABLE EMP_HW
AS SELECT * FROM EMP;

ALTER TABLE EMP_HW
ADD REMARK VARCHAR2(30);

SELECT * FROM EMP_HW;

#14장
#테이블 생성 시 NOT NULL 값 설정
CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID    VARCHAR2(20) NOT NULL,
    LOGIN_PWD   VARCHAR2(20) NOT NULL,
    TEL         VARCHAR2(20)
);

DESC TABLE_NOTNULL;

INSERT INTO TABLE_NOTNULL
VALUES('TEST_ID_01', '1234', '010-1234-5678');

INSERT INTO TABLE_NOTNULL
VALUES('TEST_ID_02', '1234', '010-1234-5678');

SELECT * FROM TABLE_NOTNULL;

# 계정 제약 확인
#14-5
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS;

#테이블을 만들 때 제약조건의 이름을 지정해서 만들기

#테이블에서 제약조건이 없는 컬럼을 제약조건 지정하기
ALTER TABLE TABLE_NOTNULL
MODIFY TEL NULL;

DESC TABLE_NOTNULL;

#FOREIGN KEY 지정하기
CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DENAME VARCHAR2(14),
    LOC    VARCHAR2(13)
);

#14-40
CREATE TABLE EMP_FK(

   DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK
          REFERENCES DEPT_FK(DEPTNO)
);
