# 급여가 3000이 아닌 어떻게 표현 ! = <> = ^= 같은 표현이다.
SELECT * FROM EMP WHERE SAL != 3000;
SELECT * FROM EMP WHERE SAL <> 3000;
SELECT * FROM EMP WHERE SAL ^= 3000;
SELECT * FROM EMP WHERE NOT SAL = 3000;

# IN 연산자 포함
# 직업이 'MANAGER' 또는 'SALESMAN' 또는 'CLERK'
SELECT * FROM EMP 
WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');

# 전체비교
SELECT * FROM EMP 
WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK');

#등가 비교 AND을 이용해서 동일하게 만들려면
SELECT * FROM EMP 
WHERE JOB !='MANAGER' AND JOB <>'SALESMAN' AND JOB ^='CLERK';

#급여가 2000 이상 3000이하
SELECT * FROM EMP 
WHERE SAL BETWEEN 2000 AND 3000;

SELECT * FROM EMP 
WHERE SAL >= 2000 AND SAL <=3000;

#문자열 포함
SELECT * FROM EMP 
WHERE ENAME LIKE 'S%';

#사원이름의 2번째 글자가 L인 사원만 출력
SELECT * FROM EMP 
WHERE ENAME LIKE '_L%';

# 사원이름에 AM 문자 포함
SELECT * FROM EMP 
WHERE ENAME LIKE '%AM%';
